### ISSUE TITLE
Microarchitecture: Logins

### ISSUE THREAD

**Issue by breuera** [SchedMD/slurm-gcp#1]
https://github.com/SchedMD/slurm-gcp/blob/2ca5bbec9d88a2b2be9d09645bf62a0d038b1a82/slurm.jinja#L132

The logins should use the microarchitecture of the compute nodes (or have an option for this):
Software builds on the logins might rely on the host arch.

**Comment by gaijin03** [comment]
Thanks for the suggestion. I've created an issue in our bugzilla to track this.
https://bugs.schedmd.com/show_bug.cgi?id=5918

**Comment by gaijin03** [comment]
Actually, see {login|compute|controller}_machine_type in the slurm.jinja.schema file. This allows you set the login nodes and computes to the same machine types.
